AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false

# Disable or relax some cops for daemon implementation
Metrics/AbcSize:
  Max: 120

Metrics/MethodLength:
  Max: 120

Metrics/ClassLength:
  Max: 320

Metrics/ModuleLength:
  Max: 160

Metrics/CyclomaticComplexity:
  Max: 22

Metrics/PerceivedComplexity:
  Max: 22

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '**/*.gemspec'

# Naming
Naming/PredicateMethod:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Layout/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Allow rescuing StandardError implicitly
Style/RescueStandardError:
  Enabled: false

# Allow non-local exit from iterators (needed for LSP protocol handling)
Lint/NonLocalExitFromIterator:
  Enabled: false

# Allow if/unless modifiers with multi-line body
Style/IfUnlessModifier:
  Enabled: false

# Allow IO.select (needed for cross-platform compatibility)
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false
